### ISSUE TITLE
データベース設計

### ISSUE THREAD

**Issue by ryushin0316** [ryushin0316/furima-33389#1]

**Comment by ryushin0316** [comment]
＃ What
データベース設計

# Why
データベース設計に必要な物を整理するため

ER図→https://gyazo.com/7d78916e0d583d30213765ff5ab123d9

**Comment by ryushin0316** [comment]
# What
データベース設計

# Why
データベース設計のためのER図の作成

ER図https://gyazo.com/7d78916e0d583d30213765ff5ab123d9

**Comment by yuri240** [comment]
レビュー依頼ありがとうございます。

いただいたプルリクエストですが、
READMEの記述が確認できず
修正点の差分があがっていないように見受けられました。

お手数おかけして大変申し訳ないのですが、
コミットとプッシュのし忘れを確認していただき
再度ご提出をお願いします。
